[2025-01-18T00:21:19.345+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.sync_data_connection_5 scheduled__2025-01-17T00:00:00+00:00 [queued]>
[2025-01-18T00:21:19.375+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.sync_data_connection_5 scheduled__2025-01-17T00:00:00+00:00 [queued]>
[2025-01-18T00:21:19.376+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-18T00:21:19.407+0000] {taskinstance.py:1382} INFO - Executing <Task(AirbyteTriggerSyncOperator): sync_data_connection_5> on 2025-01-17 00:00:00+00:00
[2025-01-18T00:21:19.417+0000] {standard_task_runner.py:57} INFO - Started process 98 to run task
[2025-01-18T00:21:19.424+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'sync_data_connection_5', 'scheduled__2025-01-17T00:00:00+00:00', '--job-id', '451', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmp8d5q1m4b']
[2025-01-18T00:21:19.432+0000] {standard_task_runner.py:85} INFO - Job 451: Subtask sync_data_connection_5
[2025-01-18T00:21:19.580+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.sync_data_connection_5 scheduled__2025-01-17T00:00:00+00:00 [running]> on host a7a323ab681c
