[2024-12-02T22:08:20.081+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.sync_polygon_data scheduled__2024-12-02T21:00:00+00:00 [queued]>
[2024-12-02T22:08:20.114+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.sync_polygon_data scheduled__2024-12-02T21:00:00+00:00 [queued]>
[2024-12-02T22:08:20.115+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-02T22:08:20.116+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-02T22:08:20.118+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-02T22:08:20.202+0000] {taskinstance.py:1300} INFO - Executing <Task(AirbyteTriggerSyncOperator): sync_polygon_data> on 2024-12-02 21:00:00+00:00
[2024-12-02T22:08:20.220+0000] {standard_task_runner.py:55} INFO - Started process 32572 to run task
[2024-12-02T22:08:20.227+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'sync_polygon_data', 'scheduled__2024-12-02T21:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_BigQuery_sync.py', '--cfg-path', '/tmp/tmp5f8_7qf9']
[2024-12-02T22:08:20.235+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask sync_polygon_data
[2024-12-02T22:08:20.495+0000] {task_command.py:388} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.sync_polygon_data scheduled__2024-12-02T21:00:00+00:00 [running]> on host 5ecff608e4ff
[2024-12-02T22:08:20.799+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PolygonAPI_to_BigQuery
AIRFLOW_CTX_TASK_ID=sync_polygon_data
AIRFLOW_CTX_EXECUTION_DATE=2024-12-02T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-02T21:00:00+00:00
[2024-12-02T22:08:20.857+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:22.026+0000] {airbyte.py:77} INFO - Job 18 was submitted to Airbyte Server
[2024-12-02T22:08:22.033+0000] {airbyte.py:79} INFO - Waiting for job 18 to complete
[2024-12-02T22:08:25.053+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:28.140+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:31.189+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:34.219+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:37.254+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:40.289+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:43.321+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:46.354+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:49.386+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:52.418+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:55.500+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:08:58.530+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:09:01.560+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:09:04.590+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:09:07.627+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:09:15.328+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:37:34.892+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:37:38.002+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:37:40.475+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-12-02T22:37:40.479+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 32572. PIDs of all processes in the group: [32572]
[2024-12-02T22:37:40.480+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 32572
[2024-12-02T22:37:40.481+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-02T22:37:40.482+0000] {airbyte.py:88} INFO - on_kill: cancel the airbyte Job 18
[2024-12-02T22:37:40.495+0000] {base.py:73} INFO - Using connection ID 'airbyte_to_bigquery' for task execution.
[2024-12-02T22:38:10.259+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 80, in execute
    self.hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 67, in wait_for_job
    time.sleep(wait_seconds)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1481, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-02T22:38:10.266+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=PolygonAPI_to_BigQuery, task_id=sync_polygon_data, execution_date=20241202T210000, start_date=20241202T220820, end_date=20241202T223810
[2024-12-02T22:38:10.279+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task sync_polygon_data (Task received SIGTERM signal; 32572)
[2024-12-02T22:38:10.324+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=32572, status='terminated', exitcode=1, started='22:08:19') (32572) terminated with exit code 1
