[2025-01-13T00:48:30.644+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:41:15.479962+00:00 [queued]>
[2025-01-13T00:48:30.655+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:41:15.479962+00:00 [queued]>
[2025-01-13T00:48:30.656+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-13T00:48:30.671+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-13 00:41:15.479962+00:00
[2025-01-13T00:48:30.678+0000] {standard_task_runner.py:57} INFO - Started process 658 to run task
[2025-01-13T00:48:30.682+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'manual__2025-01-13T00:41:15.479962+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmp97mf_i6s']
[2025-01-13T00:48:30.685+0000] {standard_task_runner.py:85} INFO - Job 314: Subtask dbt_transformation.stocks.run
[2025-01-13T00:48:30.734+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:41:15.479962+00:00 [running]> on host 8e83bd89ed82
[2025-01-13T00:48:31.002+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T00:41:15.479962+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T00:41:15.479962+00:00'
[2025-01-13T00:48:33.577+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T00:48:33.579+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpsf3gu7bq from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T00:48:33.584+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/PolygonAPI_to_BigQuery__dbt_transformation/target/partial_parse.msgpack
[2025-01-13T00:48:33.590+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T00:48:33.591+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmpsf3gu7bq', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpsf3gu7bq
[2025-01-13T00:48:33.624+0000] {eventmgr.py:60} DEBUG - [0m00:48:33.622625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf5f57a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e31850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e319a0>]}
[2025-01-13T00:48:33.625+0000] {logging_mixin.py:151} INFO - 00:48:33  Running with dbt=1.5.11
[2025-01-13T00:48:33.625+0000] {eventmgr.py:62} INFO - [0m00:48:33  Running with dbt=1.5.11
[2025-01-13T00:48:33.626+0000] {eventmgr.py:62} INFO - 

============================== 00:48:33.625315 | 1095f532-374f-480c-af86-642d91a63c27 ==============================
[0m00:48:33.625315 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T00:48:33.628+0000] {eventmgr.py:60} DEBUG - [0m00:48:33.627810 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/tmp/tmpsf3gu7bq/logs', 'version_check': 'True', 'profiles_dir': '/opt/***/dbt/profiles', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T00:48:33.961+0000] {eventmgr.py:60} DEBUG - [0m00:48:33.961282 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '1095f532-374f-480c-af86-642d91a63c27', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e39220>]}
[2025-01-13T00:48:34.000+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.000601 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '1095f532-374f-480c-af86-642d91a63c27', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceef16910>]}
[2025-01-13T00:48:34.002+0000] {logging_mixin.py:151} INFO - 00:48:34  Registered adapter: bigquery=1.5.9
[2025-01-13T00:48:34.002+0000] {eventmgr.py:62} INFO - [0m00:48:34  Registered adapter: bigquery=1.5.9
[2025-01-13T00:48:34.003+0000] {eventmgr.py:62} INFO - [0m00:48:34.002053 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T00:48:34.030+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.030341 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T00:48:34.136+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.135811 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[2025-01-13T00:48:34.137+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.136971 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[2025-01-13T00:48:34.146+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.146532 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '1095f532-374f-480c-af86-642d91a63c27', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceedd0190>]}
[2025-01-13T00:48:34.159+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.158605 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '1095f532-374f-480c-af86-642d91a63c27', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee32f70>]}
[2025-01-13T00:48:34.160+0000] {logging_mixin.py:151} INFO - 00:48:34  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:48:34.160+0000] {eventmgr.py:62} INFO - [0m00:48:34  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:48:34.161+0000] {eventmgr.py:62} INFO - [0m00:48:34.160087 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:48:34.162+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.162469 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '1095f532-374f-480c-af86-642d91a63c27', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee9a070>]}
[2025-01-13T00:48:34.164+0000] {logging_mixin.py:151} INFO - 00:48:34
[2025-01-13T00:48:34.164+0000] {eventmgr.py:62} INFO - [0m00:48:34  
[2025-01-13T00:48:34.165+0000] {eventmgr.py:62} INFO - [0m00:48:34.164405 [info ] [MainThread]: 
[2025-01-13T00:48:34.167+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.167180 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T00:48:34.169+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.169391 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T00:48:34.170+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.170597 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T00:48:34.173+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.172828 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json''
[2025-01-13T00:48:34.175+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.175181 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T00:48:34.177+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.176772 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T00:48:34.178+0000] {logging_mixin.py:151} INFO - 00:48:34
[2025-01-13T00:48:34.178+0000] {eventmgr.py:62} INFO - [0m00:48:34  
[2025-01-13T00:48:34.179+0000] {eventmgr.py:62} INFO - [0m00:48:34.178036 [info ] [MainThread]: 
[2025-01-13T00:48:34.180+0000] {logging_mixin.py:151} INFO - 00:48:34  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:48:34.180+0000] {eventmgr.py:62} INFO - [0m00:48:34  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:48:34.181+0000] {eventmgr.py:62} INFO - [0m00:48:34.180235 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:48:34.182+0000] {logging_mixin.py:151} INFO - 00:48:34  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:48:34.182+0000] {eventmgr.py:66} ERROR - [0m00:48:34  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:48:34.183+0000] {eventmgr.py:66} ERROR - [0m00:48:34.182386 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:48:34.185+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.184755 [debug] [MainThread]: Command `cli run` failed at 00:48:34.184624 after 0.59 seconds
[2025-01-13T00:48:34.186+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.185709 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf5f57a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee9a160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceedd0280>]}
[2025-01-13T00:48:34.187+0000] {eventmgr.py:60} DEBUG - [0m00:48:34.186880 [debug] [MainThread]: Flushing usage events
[2025-01-13T00:48:34.981+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T00:48:34.982+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T00:48:34.983+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T00:48:34.983+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T00:48:34.984+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T00:48:35.006+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T00:48:35.172+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:48:35.175+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250113T004115, start_date=20250113T004830, end_date=20250113T004835
[2025-01-13T00:48:35.187+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 314 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'; 658)
[2025-01-13T00:48:35.235+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T00:48:35.259+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
