[2025-01-13T00:43:24.022+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:41:15.479962+00:00 [queued]>
[2025-01-13T00:43:24.031+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:41:15.479962+00:00 [queued]>
[2025-01-13T00:43:24.032+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T00:43:24.046+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-13 00:41:15.479962+00:00
[2025-01-13T00:43:24.052+0000] {standard_task_runner.py:57} INFO - Started process 452 to run task
[2025-01-13T00:43:24.055+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'manual__2025-01-13T00:41:15.479962+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpx9ci37ne']
[2025-01-13T00:43:24.058+0000] {standard_task_runner.py:85} INFO - Job 313: Subtask dbt_transformation.stocks.run
[2025-01-13T00:43:24.101+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:41:15.479962+00:00 [running]> on host 8e83bd89ed82
[2025-01-13T00:43:24.374+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T00:41:15.479962+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T00:41:15.479962+00:00'
[2025-01-13T00:43:27.184+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T00:43:27.185+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpib43vvw9 from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T00:43:27.189+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/PolygonAPI_to_BigQuery__dbt_transformation/target/partial_parse.msgpack
[2025-01-13T00:43:27.198+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T00:43:27.199+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmpib43vvw9', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpib43vvw9
[2025-01-13T00:43:27.257+0000] {eventmgr.py:60} DEBUG - [0m00:43:27.252770 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf5f5bf40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e54f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e54820>]}
[2025-01-13T00:43:27.259+0000] {logging_mixin.py:151} INFO - 00:43:27  Running with dbt=1.5.11
[2025-01-13T00:43:27.258+0000] {eventmgr.py:62} INFO - [0m00:43:27  Running with dbt=1.5.11
[2025-01-13T00:43:27.261+0000] {eventmgr.py:62} INFO - 

============================== 00:43:27.258294 | 2c32d54e-abd3-4321-a44a-734275b745ad ==============================
[0m00:43:27.258294 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T00:43:27.263+0000] {eventmgr.py:60} DEBUG - [0m00:43:27.262399 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/tmp/tmpib43vvw9/logs', 'version_check': 'True', 'profiles_dir': '/opt/***/dbt/profiles', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T00:43:27.947+0000] {eventmgr.py:60} DEBUG - [0m00:43:27.946442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '2c32d54e-abd3-4321-a44a-734275b745ad', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e546d0>]}
[2025-01-13T00:43:28.019+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.018932 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '2c32d54e-abd3-4321-a44a-734275b745ad', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceefb4730>]}
[2025-01-13T00:43:28.022+0000] {logging_mixin.py:151} INFO - 00:43:28  Registered adapter: bigquery=1.5.9
[2025-01-13T00:43:28.022+0000] {eventmgr.py:62} INFO - [0m00:43:28  Registered adapter: bigquery=1.5.9
[2025-01-13T00:43:28.023+0000] {eventmgr.py:62} INFO - [0m00:43:28.021732 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T00:43:28.066+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.065618 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T00:43:28.258+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.257414 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[2025-01-13T00:43:28.259+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.258859 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[2025-01-13T00:43:28.272+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.272214 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '2c32d54e-abd3-4321-a44a-734275b745ad', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceedd4670>]}
[2025-01-13T00:43:28.288+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.287994 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '2c32d54e-abd3-4321-a44a-734275b745ad', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee41400>]}
[2025-01-13T00:43:28.289+0000] {logging_mixin.py:151} INFO - 00:43:28  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:43:28.289+0000] {eventmgr.py:62} INFO - [0m00:43:28  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:43:28.290+0000] {eventmgr.py:62} INFO - [0m00:43:28.289199 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T00:43:28.291+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.291098 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '2c32d54e-abd3-4321-a44a-734275b745ad', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee414c0>]}
[2025-01-13T00:43:28.293+0000] {logging_mixin.py:151} INFO - 00:43:28
[2025-01-13T00:43:28.293+0000] {eventmgr.py:62} INFO - [0m00:43:28  
[2025-01-13T00:43:28.294+0000] {eventmgr.py:62} INFO - [0m00:43:28.293141 [info ] [MainThread]: 
[2025-01-13T00:43:28.296+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.295712 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T00:43:28.299+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.298424 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T00:43:28.300+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.300006 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T00:43:28.302+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.302458 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json''
[2025-01-13T00:43:28.305+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.304928 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T00:43:28.306+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.305953 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T00:43:28.307+0000] {logging_mixin.py:151} INFO - 00:43:28
[2025-01-13T00:43:28.307+0000] {eventmgr.py:62} INFO - [0m00:43:28  
[2025-01-13T00:43:28.308+0000] {eventmgr.py:62} INFO - [0m00:43:28.306799 [info ] [MainThread]: 
[2025-01-13T00:43:28.309+0000] {logging_mixin.py:151} INFO - 00:43:28  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:43:28.308+0000] {eventmgr.py:62} INFO - [0m00:43:28  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:43:28.309+0000] {eventmgr.py:62} INFO - [0m00:43:28.308605 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T00:43:28.311+0000] {logging_mixin.py:151} INFO - 00:43:28  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:43:28.311+0000] {eventmgr.py:66} ERROR - [0m00:43:28  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:43:28.312+0000] {eventmgr.py:66} ERROR - [0m00:43:28.310635 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:43:28.313+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.312848 [debug] [MainThread]: Command `cli run` failed at 00:43:28.312658 after 1.10 seconds
[2025-01-13T00:43:28.314+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.314393 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf5f5bf40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee416a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee41160>]}
[2025-01-13T00:43:28.316+0000] {eventmgr.py:60} DEBUG - [0m00:43:28.315818 [debug] [MainThread]: Flushing usage events
[2025-01-13T00:43:29.160+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T00:43:29.162+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T00:43:29.162+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T00:43:29.163+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T00:43:29.163+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T00:43:29.188+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T00:43:29.393+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'
[2025-01-13T00:43:29.400+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250113T004115, start_date=20250113T004324, end_date=20250113T004329
[2025-01-13T00:43:29.413+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 313 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/***/stock-market-elt-key.json'; 452)
[2025-01-13T00:43:29.439+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T00:43:29.472+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
