[2025-01-13T03:00:58.476+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T02:59:22.940216+00:00 [queued]>
[2025-01-13T03:00:58.486+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T02:59:22.940216+00:00 [queued]>
[2025-01-13T03:00:58.487+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T03:00:58.501+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-13 02:59:22.940216+00:00
[2025-01-13T03:00:58.508+0000] {standard_task_runner.py:57} INFO - Started process 3137 to run task
[2025-01-13T03:00:58.511+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'manual__2025-01-13T02:59:22.940216+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmp2tcpib36']
[2025-01-13T03:00:58.516+0000] {standard_task_runner.py:85} INFO - Job 342: Subtask dbt_transformation.stocks.run
[2025-01-13T03:00:58.566+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T02:59:22.940216+00:00 [running]> on host 5bdaf9e12d64
[2025-01-13T03:00:58.934+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T02:59:22.940216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T02:59:22.940216+00:00'
[2025-01-13T03:01:02.149+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T03:01:02.151+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp47at4gv8 from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T03:01:02.158+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/PolygonAPI_to_BigQuery__dbt_transformation/target/partial_parse.msgpack
[2025-01-13T03:01:02.167+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T03:01:02.169+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmp47at4gv8', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmp47at4gv8
[2025-01-13T03:01:02.216+0000] {eventmgr.py:60} DEBUG - [0m03:01:02.213470 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e7149d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d6a9670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d6a97c0>]}
[2025-01-13T03:01:02.217+0000] {logging_mixin.py:151} INFO - 03:01:02  Running with dbt=1.5.11
[2025-01-13T03:01:02.217+0000] {eventmgr.py:62} INFO - [0m03:01:02  Running with dbt=1.5.11
[2025-01-13T03:01:02.218+0000] {eventmgr.py:62} INFO - 

============================== 03:01:02.216742 | 2c593383-f0d9-4874-b57b-f156ef86800d ==============================
[0m03:01:02.216742 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T03:01:02.219+0000] {eventmgr.py:60} DEBUG - [0m03:01:02.219008 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/***/dbt/profiles', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': '/tmp/tmp47at4gv8/logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T03:01:02.837+0000] {eventmgr.py:60} DEBUG - [0m03:01:02.837313 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '2c593383-f0d9-4874-b57b-f156ef86800d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d6a7a00>]}
[2025-01-13T03:01:02.880+0000] {eventmgr.py:60} DEBUG - [0m03:01:02.879751 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '2c593383-f0d9-4874-b57b-f156ef86800d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677ec5b0>]}
[2025-01-13T03:01:02.882+0000] {logging_mixin.py:151} INFO - 03:01:02  Registered adapter: bigquery=1.5.9
[2025-01-13T03:01:02.882+0000] {eventmgr.py:62} INFO - [0m03:01:02  Registered adapter: bigquery=1.5.9
[2025-01-13T03:01:02.883+0000] {eventmgr.py:62} INFO - [0m03:01:02.881662 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T03:01:02.915+0000] {eventmgr.py:60} DEBUG - [0m03:01:02.914986 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T03:01:02.936+0000] {logging_mixin.py:151} INFO - 03:01:02  Unable to do partial parsing because profile has changed
[2025-01-13T03:01:02.936+0000] {eventmgr.py:62} INFO - [0m03:01:02  Unable to do partial parsing because profile has changed
[2025-01-13T03:01:02.937+0000] {eventmgr.py:62} INFO - [0m03:01:02.935887 [info ] [MainThread]: Unable to do partial parsing because profile has changed
[2025-01-13T03:01:02.938+0000] {eventmgr.py:60} DEBUG - [0m03:01:02.938536 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '2c593383-f0d9-4874-b57b-f156ef86800d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc867796e20>]}
[2025-01-13T03:01:04.396+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.395798 [debug] [MainThread]: 1699: static parser successfully parsed stocks.sql
[2025-01-13T03:01:04.932+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.931589 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '2c593383-f0d9-4874-b57b-f156ef86800d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8665f35b0>]}
[2025-01-13T03:01:04.952+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.951683 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '2c593383-f0d9-4874-b57b-f156ef86800d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677084c0>]}
[2025-01-13T03:01:04.956+0000] {logging_mixin.py:151} INFO - 03:01:04  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T03:01:04.955+0000] {eventmgr.py:62} INFO - [0m03:01:04  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T03:01:04.957+0000] {eventmgr.py:62} INFO - [0m03:01:04.954452 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T03:01:04.959+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.958636 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '2c593383-f0d9-4874-b57b-f156ef86800d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8676d6f70>]}
[2025-01-13T03:01:04.962+0000] {logging_mixin.py:151} INFO - 03:01:04
[2025-01-13T03:01:04.962+0000] {eventmgr.py:62} INFO - [0m03:01:04  
[2025-01-13T03:01:04.963+0000] {eventmgr.py:62} INFO - [0m03:01:04.961460 [info ] [MainThread]: 
[2025-01-13T03:01:04.968+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.967419 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T03:01:04.972+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.971473 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T03:01:04.973+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.973309 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T03:01:04.975+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.974625 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 2] No such file or directory: 'C:\\Users\\Khaled\\Khaled\\Desktop\\stock_market-project\\stock-market-elt-key.json''
[2025-01-13T03:01:04.978+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.977842 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T03:01:04.979+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.979356 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T03:01:04.981+0000] {logging_mixin.py:151} INFO - 03:01:04
[2025-01-13T03:01:04.981+0000] {eventmgr.py:62} INFO - [0m03:01:04  
[2025-01-13T03:01:04.982+0000] {eventmgr.py:62} INFO - [0m03:01:04.980527 [info ] [MainThread]: 
[2025-01-13T03:01:04.983+0000] {logging_mixin.py:151} INFO - 03:01:04  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T03:01:04.983+0000] {eventmgr.py:62} INFO - [0m03:01:04  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T03:01:04.984+0000] {eventmgr.py:62} INFO - [0m03:01:04.982772 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T03:01:04.986+0000] {logging_mixin.py:151} INFO - 03:01:04  Encountered an error:
Database Error
  [Errno 2] No such file or directory: 'C:\\Users\\Khaled\\Khaled\\Desktop\\stock_market-project\\stock-market-elt-key.json'
[2025-01-13T03:01:04.986+0000] {eventmgr.py:66} ERROR - [0m03:01:04  Encountered an error:
Database Error
  [Errno 2] No such file or directory: 'C:\\Users\\Khaled\\Khaled\\Desktop\\stock_market-project\\stock-market-elt-key.json'
[2025-01-13T03:01:04.987+0000] {eventmgr.py:66} ERROR - [0m03:01:04.985791 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 2] No such file or directory: 'C:\\Users\\Khaled\\Khaled\\Desktop\\stock_market-project\\stock-market-elt-key.json'
[2025-01-13T03:01:04.989+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.988878 [debug] [MainThread]: Command `cli run` failed at 03:01:04.988657 after 2.81 seconds
[2025-01-13T03:01:04.990+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.990281 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e7149d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc867796850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc867738730>]}
[2025-01-13T03:01:04.992+0000] {eventmgr.py:60} DEBUG - [0m03:01:04.991472 [debug] [MainThread]: Flushing usage events
[2025-01-13T03:01:05.777+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T03:01:05.778+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T03:01:05.779+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T03:01:05.779+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T03:01:05.780+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T03:01:05.813+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T03:01:05.856+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 2] No such file or directory: 'C:\\Users\\Khaled\\Khaled\\Desktop\\stock_market-project\\stock-market-elt-key.json'
[2025-01-13T03:01:05.861+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250113T025922, start_date=20250113T030058, end_date=20250113T030105
[2025-01-13T03:01:05.874+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 342 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 2] No such file or directory: 'C:\\Users\\Khaled\\Khaled\\Desktop\\stock_market-project\\stock-market-elt-key.json'; 3137)
[2025-01-13T03:01:05.900+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T03:01:05.928+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
