[2025-01-18T13:40:36.243+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: PolygonAPI_to_BigQuery.sync_data_connection_3 manual__2025-01-18T00:58:32.788564+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-01-18T13:40:36.268+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
