[2025-01-13T01:09:01.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:51:41.017426+00:00 [queued]>
[2025-01-13T01:09:01.661+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:51:41.017426+00:00 [queued]>
[2025-01-13T01:09:01.661+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-13T01:09:01.676+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-13 00:51:41.017426+00:00
[2025-01-13T01:09:01.682+0000] {standard_task_runner.py:57} INFO - Started process 1591 to run task
[2025-01-13T01:09:01.685+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'manual__2025-01-13T00:51:41.017426+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpbhmslw7o']
[2025-01-13T01:09:01.688+0000] {standard_task_runner.py:85} INFO - Job 321: Subtask dbt_transformation.stocks.run
[2025-01-13T01:09:01.734+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T00:51:41.017426+00:00 [running]> on host 8e83bd89ed82
[2025-01-13T01:09:01.997+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T00:51:41.017426+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T00:51:41.017426+00:00'
[2025-01-13T01:09:04.613+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T01:09:04.614+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpm6ala6k2 from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T01:09:04.620+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/PolygonAPI_to_BigQuery__dbt_transformation/target/partial_parse.msgpack
[2025-01-13T01:09:04.626+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T01:09:04.628+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmpm6ala6k2', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpm6ala6k2
[2025-01-13T01:09:04.667+0000] {eventmgr.py:60} DEBUG - [0m01:09:04.665363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf5f57a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e31850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e319a0>]}
[2025-01-13T01:09:04.669+0000] {logging_mixin.py:151} INFO - 01:09:04  Running with dbt=1.5.11
[2025-01-13T01:09:04.669+0000] {eventmgr.py:62} INFO - [0m01:09:04  Running with dbt=1.5.11
[2025-01-13T01:09:04.670+0000] {eventmgr.py:62} INFO - 

============================== 01:09:04.668717 | 4ae9c8c6-a91c-46af-9152-f71ff97799c8 ==============================
[0m01:09:04.668717 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T01:09:04.671+0000] {eventmgr.py:60} DEBUG - [0m01:09:04.671142 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/tmp/tmpm6ala6k2/logs', 'version_check': 'True', 'profiles_dir': '/opt/***/dbt/profiles', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T01:09:05.059+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.059210 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '4ae9c8c6-a91c-46af-9152-f71ff97799c8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf4e39220>]}
[2025-01-13T01:09:05.098+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.097750 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '4ae9c8c6-a91c-46af-9152-f71ff97799c8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceef16910>]}
[2025-01-13T01:09:05.099+0000] {logging_mixin.py:151} INFO - 01:09:05  Registered adapter: bigquery=1.5.9
[2025-01-13T01:09:05.099+0000] {eventmgr.py:62} INFO - [0m01:09:05  Registered adapter: bigquery=1.5.9
[2025-01-13T01:09:05.100+0000] {eventmgr.py:62} INFO - [0m01:09:05.099208 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T01:09:05.129+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.129554 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T01:09:05.246+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.246141 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[2025-01-13T01:09:05.247+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.247289 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[2025-01-13T01:09:05.257+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.256648 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '4ae9c8c6-a91c-46af-9152-f71ff97799c8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceedd0190>]}
[2025-01-13T01:09:05.268+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.267996 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '4ae9c8c6-a91c-46af-9152-f71ff97799c8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee32f70>]}
[2025-01-13T01:09:05.269+0000] {logging_mixin.py:151} INFO - 01:09:05  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:09:05.269+0000] {eventmgr.py:62} INFO - [0m01:09:05  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:09:05.270+0000] {eventmgr.py:62} INFO - [0m01:09:05.269300 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:09:05.271+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.271644 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '4ae9c8c6-a91c-46af-9152-f71ff97799c8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee99070>]}
[2025-01-13T01:09:05.273+0000] {logging_mixin.py:151} INFO - 01:09:05
[2025-01-13T01:09:05.273+0000] {eventmgr.py:62} INFO - [0m01:09:05  
[2025-01-13T01:09:05.275+0000] {eventmgr.py:62} INFO - [0m01:09:05.273470 [info ] [MainThread]: 
[2025-01-13T01:09:05.276+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.276242 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T01:09:05.278+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.278225 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T01:09:05.279+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.279247 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T01:09:05.280+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.280239 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 2] No such file or directory: '/opt/stock-market-elt-key.json''
[2025-01-13T01:09:05.282+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.282317 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T01:09:05.283+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.283197 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T01:09:05.284+0000] {logging_mixin.py:151} INFO - 01:09:05
[2025-01-13T01:09:05.284+0000] {eventmgr.py:62} INFO - [0m01:09:05  
[2025-01-13T01:09:05.285+0000] {eventmgr.py:62} INFO - [0m01:09:05.284097 [info ] [MainThread]: 
[2025-01-13T01:09:05.286+0000] {logging_mixin.py:151} INFO - 01:09:05  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:09:05.286+0000] {eventmgr.py:62} INFO - [0m01:09:05  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:09:05.287+0000] {eventmgr.py:62} INFO - [0m01:09:05.286233 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:09:05.288+0000] {logging_mixin.py:151} INFO - 01:09:05  Encountered an error:
Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:09:05.288+0000] {eventmgr.py:66} ERROR - [0m01:09:05  Encountered an error:
Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:09:05.290+0000] {eventmgr.py:66} ERROR - [0m01:09:05.288545 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:09:05.291+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.290949 [debug] [MainThread]: Command `cli run` failed at 01:09:05.290827 after 0.66 seconds
[2025-01-13T01:09:05.292+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.292002 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbcf5f57a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceee99160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fbceedd0280>]}
[2025-01-13T01:09:05.293+0000] {eventmgr.py:60} DEBUG - [0m01:09:05.293178 [debug] [MainThread]: Flushing usage events
[2025-01-13T01:09:06.095+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T01:09:06.096+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T01:09:06.097+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T01:09:06.097+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T01:09:06.098+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T01:09:06.122+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T01:09:06.296+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:09:06.300+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250113T005141, start_date=20250113T010901, end_date=20250113T010906
[2025-01-13T01:09:06.313+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 321 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'; 1591)
[2025-01-13T01:09:06.357+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T01:09:06.384+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
