[2025-01-13T02:56:41.649+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T02:54:58.780813+00:00 [queued]>
[2025-01-13T02:56:41.663+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T02:54:58.780813+00:00 [queued]>
[2025-01-13T02:56:41.664+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T02:56:41.679+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-13 02:54:58.780813+00:00
[2025-01-13T02:56:41.685+0000] {standard_task_runner.py:57} INFO - Started process 2966 to run task
[2025-01-13T02:56:41.689+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'manual__2025-01-13T02:54:58.780813+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpe7b92v6l']
[2025-01-13T02:56:41.693+0000] {standard_task_runner.py:85} INFO - Job 336: Subtask dbt_transformation.stocks.run
[2025-01-13T02:56:41.757+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T02:54:58.780813+00:00 [running]> on host 5bdaf9e12d64
[2025-01-13T02:56:42.082+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T02:54:58.780813+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T02:54:58.780813+00:00'
[2025-01-13T02:56:45.067+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T02:56:45.069+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmphgwom2aq from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T02:56:45.074+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/PolygonAPI_to_BigQuery__dbt_transformation/target/partial_parse.msgpack
[2025-01-13T02:56:45.087+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T02:56:45.088+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmphgwom2aq', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmphgwom2aq
[2025-01-13T02:56:45.134+0000] {eventmgr.py:60} DEBUG - [0m02:56:45.131259 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e70ad90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d708c40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d708d90>]}
[2025-01-13T02:56:45.136+0000] {logging_mixin.py:151} INFO - 02:56:45  Running with dbt=1.5.11
[2025-01-13T02:56:45.136+0000] {eventmgr.py:62} INFO - [0m02:56:45  Running with dbt=1.5.11
[2025-01-13T02:56:45.137+0000] {eventmgr.py:62} INFO - 

============================== 02:56:45.135668 | ccf35bf7-291d-4ab6-b827-463ea4f43f9c ==============================
[0m02:56:45.135668 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T02:56:45.139+0000] {eventmgr.py:60} DEBUG - [0m02:56:45.139155 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/***/dbt/profiles', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': '/tmp/tmphgwom2aq/logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T02:56:45.851+0000] {eventmgr.py:60} DEBUG - [0m02:56:45.850552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'ccf35bf7-291d-4ab6-b827-463ea4f43f9c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d72e5b0>]}
[2025-01-13T02:56:45.897+0000] {eventmgr.py:60} DEBUG - [0m02:56:45.896591 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'ccf35bf7-291d-4ab6-b827-463ea4f43f9c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677cdf10>]}
[2025-01-13T02:56:45.899+0000] {logging_mixin.py:151} INFO - 02:56:45  Registered adapter: bigquery=1.5.9
[2025-01-13T02:56:45.899+0000] {eventmgr.py:62} INFO - [0m02:56:45  Registered adapter: bigquery=1.5.9
[2025-01-13T02:56:45.900+0000] {eventmgr.py:62} INFO - [0m02:56:45.898766 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T02:56:45.931+0000] {eventmgr.py:60} DEBUG - [0m02:56:45.930616 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T02:56:46.183+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.182982 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[2025-01-13T02:56:46.184+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.184219 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[2025-01-13T02:56:46.196+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.196061 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'ccf35bf7-291d-4ab6-b827-463ea4f43f9c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86767b460>]}
[2025-01-13T02:56:46.211+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.210641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'ccf35bf7-291d-4ab6-b827-463ea4f43f9c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8676df1f0>]}
[2025-01-13T02:56:46.212+0000] {logging_mixin.py:151} INFO - 02:56:46  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T02:56:46.212+0000] {eventmgr.py:62} INFO - [0m02:56:46  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T02:56:46.213+0000] {eventmgr.py:62} INFO - [0m02:56:46.212070 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T02:56:46.214+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.214363 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ccf35bf7-291d-4ab6-b827-463ea4f43f9c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8676df2b0>]}
[2025-01-13T02:56:46.217+0000] {logging_mixin.py:151} INFO - 02:56:46
[2025-01-13T02:56:46.217+0000] {eventmgr.py:62} INFO - [0m02:56:46  
[2025-01-13T02:56:46.218+0000] {eventmgr.py:62} INFO - [0m02:56:46.216580 [info ] [MainThread]: 
[2025-01-13T02:56:46.220+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.219747 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T02:56:46.222+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.222380 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T02:56:46.224+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.224051 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T02:56:46.226+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.226319 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 2] No such file or directory: '/opt/stock-market-elt-key.json''
[2025-01-13T02:56:46.229+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.228985 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T02:56:46.230+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.230091 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T02:56:46.231+0000] {logging_mixin.py:151} INFO - 02:56:46
[2025-01-13T02:56:46.231+0000] {eventmgr.py:62} INFO - [0m02:56:46  
[2025-01-13T02:56:46.232+0000] {eventmgr.py:62} INFO - [0m02:56:46.231096 [info ] [MainThread]: 
[2025-01-13T02:56:46.233+0000] {logging_mixin.py:151} INFO - 02:56:46  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T02:56:46.233+0000] {eventmgr.py:62} INFO - [0m02:56:46  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T02:56:46.235+0000] {eventmgr.py:62} INFO - [0m02:56:46.233411 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T02:56:46.236+0000] {logging_mixin.py:151} INFO - 02:56:46  Encountered an error:
Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T02:56:46.236+0000] {eventmgr.py:66} ERROR - [0m02:56:46  Encountered an error:
Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T02:56:46.237+0000] {eventmgr.py:66} ERROR - [0m02:56:46.235967 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T02:56:46.239+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.238684 [debug] [MainThread]: Command `cli run` failed at 02:56:46.238501 after 1.14 seconds
[2025-01-13T02:56:46.240+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.239858 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e70ad90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8676df430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677a5580>]}
[2025-01-13T02:56:46.241+0000] {eventmgr.py:60} DEBUG - [0m02:56:46.241321 [debug] [MainThread]: Flushing usage events
[2025-01-13T02:56:47.022+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T02:56:47.023+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T02:56:47.024+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T02:56:47.024+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T02:56:47.025+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T02:56:47.218+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T02:56:47.251+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'
[2025-01-13T02:56:47.256+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250113T025458, start_date=20250113T025641, end_date=20250113T025647
[2025-01-13T02:56:47.269+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 336 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 2] No such file or directory: '/opt/stock-market-elt-key.json'; 2966)
[2025-01-13T02:56:47.314+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T02:56:47.343+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
