[2025-01-13T01:52:14.899+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T01:44:36.577217+00:00 [queued]>
[2025-01-13T01:52:14.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T01:44:36.577217+00:00 [queued]>
[2025-01-13T01:52:14.912+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-13T01:52:14.929+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-13 01:44:36.577217+00:00
[2025-01-13T01:52:14.936+0000] {standard_task_runner.py:57} INFO - Started process 445 to run task
[2025-01-13T01:52:14.939+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'manual__2025-01-13T01:44:36.577217+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpxrl4q855']
[2025-01-13T01:52:14.943+0000] {standard_task_runner.py:85} INFO - Job 330: Subtask dbt_transformation.stocks.run
[2025-01-13T01:52:14.995+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T01:44:36.577217+00:00 [running]> on host 5bdaf9e12d64
[2025-01-13T01:52:15.273+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T01:44:36.577217+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T01:44:36.577217+00:00'
[2025-01-13T01:52:17.618+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T01:52:17.619+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpkxhcnzth from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T01:52:17.625+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/PolygonAPI_to_BigQuery__dbt_transformation/target/partial_parse.msgpack
[2025-01-13T01:52:17.631+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T01:52:17.632+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmpkxhcnzth', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpkxhcnzth
[2025-01-13T01:52:17.672+0000] {eventmgr.py:60} DEBUG - [0m01:52:17.670621 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e6e54f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d6a9100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d6a9250>]}
[2025-01-13T01:52:17.673+0000] {logging_mixin.py:151} INFO - 01:52:17  Running with dbt=1.5.11
[2025-01-13T01:52:17.673+0000] {eventmgr.py:62} INFO - [0m01:52:17  Running with dbt=1.5.11
[2025-01-13T01:52:17.674+0000] {eventmgr.py:62} INFO - 

============================== 01:52:17.673428 | 4b7432f4-90aa-433c-b615-6f9467aa2473 ==============================
[0m01:52:17.673428 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T01:52:17.676+0000] {eventmgr.py:60} DEBUG - [0m01:52:17.675742 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/***/dbt/profiles', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': '/tmp/tmpkxhcnzth/logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T01:52:18.060+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.060311 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '4b7432f4-90aa-433c-b615-6f9467aa2473', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d6a93d0>]}
[2025-01-13T01:52:18.105+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.104840 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '4b7432f4-90aa-433c-b615-6f9467aa2473', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677e4880>]}
[2025-01-13T01:52:18.106+0000] {logging_mixin.py:151} INFO - 01:52:18  Registered adapter: bigquery=1.5.9
[2025-01-13T01:52:18.106+0000] {eventmgr.py:62} INFO - [0m01:52:18  Registered adapter: bigquery=1.5.9
[2025-01-13T01:52:18.107+0000] {eventmgr.py:62} INFO - [0m01:52:18.106353 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T01:52:18.136+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.135712 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T01:52:18.275+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.274948 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[2025-01-13T01:52:18.276+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.276222 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[2025-01-13T01:52:18.288+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.287604 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '4b7432f4-90aa-433c-b615-6f9467aa2473', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc867678b50>]}
[2025-01-13T01:52:18.301+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.301091 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '4b7432f4-90aa-433c-b615-6f9467aa2473', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677388e0>]}
[2025-01-13T01:52:18.303+0000] {logging_mixin.py:151} INFO - 01:52:18  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:52:18.303+0000] {eventmgr.py:62} INFO - [0m01:52:18  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:52:18.304+0000] {eventmgr.py:62} INFO - [0m01:52:18.302797 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:52:18.305+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.305346 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '4b7432f4-90aa-433c-b615-6f9467aa2473', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677389a0>]}
[2025-01-13T01:52:18.308+0000] {logging_mixin.py:151} INFO - 01:52:18
[2025-01-13T01:52:18.307+0000] {eventmgr.py:62} INFO - [0m01:52:18  
[2025-01-13T01:52:18.309+0000] {eventmgr.py:62} INFO - [0m01:52:18.307619 [info ] [MainThread]: 
[2025-01-13T01:52:18.311+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.310704 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T01:52:18.313+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.312958 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T01:52:18.314+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.314123 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T01:52:18.317+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.316732 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 21] Is a directory: '/opt/stock-market-elt-key.json''
[2025-01-13T01:52:18.320+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.319760 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T01:52:18.321+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.320913 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T01:52:18.322+0000] {logging_mixin.py:151} INFO - 01:52:18
[2025-01-13T01:52:18.322+0000] {eventmgr.py:62} INFO - [0m01:52:18  
[2025-01-13T01:52:18.323+0000] {eventmgr.py:62} INFO - [0m01:52:18.321995 [info ] [MainThread]: 
[2025-01-13T01:52:18.324+0000] {logging_mixin.py:151} INFO - 01:52:18  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:52:18.324+0000] {eventmgr.py:62} INFO - [0m01:52:18  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:52:18.326+0000] {eventmgr.py:62} INFO - [0m01:52:18.324364 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:52:18.327+0000] {logging_mixin.py:151} INFO - 01:52:18  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:52:18.327+0000] {eventmgr.py:66} ERROR - [0m01:52:18  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:52:18.328+0000] {eventmgr.py:66} ERROR - [0m01:52:18.326793 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:52:18.329+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.329348 [debug] [MainThread]: Command `cli run` failed at 01:52:18.329190 after 0.69 seconds
[2025-01-13T01:52:18.330+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.330477 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e6e54f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc867738b80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8677387f0>]}
[2025-01-13T01:52:18.332+0000] {eventmgr.py:60} DEBUG - [0m01:52:18.331948 [debug] [MainThread]: Flushing usage events
[2025-01-13T01:52:19.106+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T01:52:19.107+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T01:52:19.108+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T01:52:19.108+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T01:52:19.109+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T01:52:19.135+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T01:52:19.323+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:52:19.328+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250113T014436, start_date=20250113T015214, end_date=20250113T015219
[2025-01-13T01:52:19.342+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 330 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'; 445)
[2025-01-13T01:52:19.369+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T01:52:19.403+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
