[2025-01-13T01:46:58.446+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T01:44:36.577217+00:00 [queued]>
[2025-01-13T01:46:58.454+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T01:44:36.577217+00:00 [queued]>
[2025-01-13T01:46:58.454+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T01:46:58.466+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.run> on 2025-01-13 01:44:36.577217+00:00
[2025-01-13T01:46:58.472+0000] {standard_task_runner.py:57} INFO - Started process 221 to run task
[2025-01-13T01:46:58.475+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.run', 'manual__2025-01-13T01:44:36.577217+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpytg6ykjb']
[2025-01-13T01:46:58.478+0000] {standard_task_runner.py:85} INFO - Job 329: Subtask dbt_transformation.stocks.run
[2025-01-13T01:46:58.519+0000] {task_command.py:415} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.run manual__2025-01-13T01:44:36.577217+00:00 [running]> on host 5bdaf9e12d64
[2025-01-13T01:46:58.806+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PolygonAPI_to_BigQuery' AIRFLOW_CTX_TASK_ID='dbt_transformation.stocks.run' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T01:44:36.577217+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T01:44:36.577217+00:00'
[2025-01-13T01:47:01.563+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-01-13T01:47:01.564+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp2w85nxcu from /opt/airflow/dbt/dbt_stock_project
[2025-01-13T01:47:01.569+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /opt/airflow/dbt/dbt_stock_project/target/partial_parse.msgpack
[2025-01-13T01:47:01.594+0000] {config.py:342} INFO - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml
[2025-01-13T01:47:01.595+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stocks', '--project-dir', '/tmp/tmp2w85nxcu', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
 in /tmp/tmp2w85nxcu
[2025-01-13T01:47:01.638+0000] {eventmgr.py:60} DEBUG - [0m01:47:01.623918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e8ce160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d67c8b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d67c670>]}
[2025-01-13T01:47:01.640+0000] {logging_mixin.py:151} INFO - 01:47:01  Running with dbt=1.5.11
[2025-01-13T01:47:01.640+0000] {eventmgr.py:62} INFO - [0m01:47:01  Running with dbt=1.5.11
[2025-01-13T01:47:01.641+0000] {eventmgr.py:62} INFO - 

============================== 01:47:01.639848 | ff89a4b5-9070-4724-a31c-0cb2bee8aa4d ==============================
[0m01:47:01.639848 [info ] [MainThread]: Running with dbt=1.5.11
[2025-01-13T01:47:01.642+0000] {eventmgr.py:60} DEBUG - [0m01:47:01.641944 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/***/dbt/profiles', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': '/tmp/tmp2w85nxcu/logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[2025-01-13T01:47:02.740+0000] {eventmgr.py:60} DEBUG - [0m01:47:02.739582 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'ff89a4b5-9070-4724-a31c-0cb2bee8aa4d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86d67c070>]}
[2025-01-13T01:47:02.785+0000] {eventmgr.py:60} DEBUG - [0m01:47:02.784552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'ff89a4b5-9070-4724-a31c-0cb2bee8aa4d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8675856a0>]}
[2025-01-13T01:47:02.787+0000] {logging_mixin.py:151} INFO - 01:47:02  Registered adapter: bigquery=1.5.9
[2025-01-13T01:47:02.786+0000] {eventmgr.py:62} INFO - [0m01:47:02  Registered adapter: bigquery=1.5.9
[2025-01-13T01:47:02.788+0000] {eventmgr.py:62} INFO - [0m01:47:02.786529 [info ] [MainThread]: Registered adapter: bigquery=1.5.9
[2025-01-13T01:47:02.817+0000] {eventmgr.py:60} DEBUG - [0m01:47:02.817591 [debug] [MainThread]: checksum: f14fb70d4f628ddd6946249d2976132253e920cfc3d8f34b2f21b58b69b506a6, vars: {}, profile: default, target: dev, version: 1.5.11
[2025-01-13T01:47:02.987+0000] {logging_mixin.py:151} INFO - 01:47:02  Unable to do partial parsing because of a version mismatch
[2025-01-13T01:47:02.987+0000] {eventmgr.py:62} INFO - [0m01:47:02  Unable to do partial parsing because of a version mismatch
[2025-01-13T01:47:02.988+0000] {eventmgr.py:62} INFO - [0m01:47:02.986948 [info ] [MainThread]: Unable to do partial parsing because of a version mismatch
[2025-01-13T01:47:02.990+0000] {eventmgr.py:60} DEBUG - [0m01:47:02.989687 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'ff89a4b5-9070-4724-a31c-0cb2bee8aa4d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86767a220>]}
[2025-01-13T01:47:04.930+0000] {eventmgr.py:60} DEBUG - [0m01:47:04.930006 [debug] [MainThread]: 1699: static parser successfully parsed stocks.sql
[2025-01-13T01:47:05.190+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.189935 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'ff89a4b5-9070-4724-a31c-0cb2bee8aa4d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86651ccd0>]}
[2025-01-13T01:47:05.203+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.202538 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'ff89a4b5-9070-4724-a31c-0cb2bee8aa4d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc8676dfe50>]}
[2025-01-13T01:47:05.204+0000] {logging_mixin.py:151} INFO - 01:47:05  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:47:05.204+0000] {eventmgr.py:62} INFO - [0m01:47:05  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:47:05.205+0000] {eventmgr.py:62} INFO - [0m01:47:05.203909 [info ] [MainThread]: Found 1 model, 2 tests, 0 snapshots, 0 analyses, 361 macros, 0 operations, 0 seed files, 5 sources, 0 exposures, 0 metrics, 0 groups
[2025-01-13T01:47:05.206+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.206381 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'ff89a4b5-9070-4724-a31c-0cb2bee8aa4d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc867806b50>]}
[2025-01-13T01:47:05.209+0000] {logging_mixin.py:151} INFO - 01:47:05
[2025-01-13T01:47:05.208+0000] {eventmgr.py:62} INFO - [0m01:47:05  
[2025-01-13T01:47:05.210+0000] {eventmgr.py:62} INFO - [0m01:47:05.208616 [info ] [MainThread]: 
[2025-01-13T01:47:05.211+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.211577 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[2025-01-13T01:47:05.214+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.213813 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_stock-market-elt'
[2025-01-13T01:47:05.215+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.215031 [debug] [ThreadPool]: Opening a new connection, currently in state init
[2025-01-13T01:47:05.218+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.217896 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 21] Is a directory: '/opt/stock-market-elt-key.json''
[2025-01-13T01:47:05.220+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.220262 [debug] [MainThread]: Connection 'master' was properly closed.
[2025-01-13T01:47:05.221+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.221481 [debug] [MainThread]: Connection 'list_stock-market-elt' was properly closed.
[2025-01-13T01:47:05.222+0000] {logging_mixin.py:151} INFO - 01:47:05
[2025-01-13T01:47:05.222+0000] {eventmgr.py:62} INFO - [0m01:47:05  
[2025-01-13T01:47:05.224+0000] {eventmgr.py:62} INFO - [0m01:47:05.222492 [info ] [MainThread]: 
[2025-01-13T01:47:05.225+0000] {logging_mixin.py:151} INFO - 01:47:05  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:47:05.225+0000] {eventmgr.py:62} INFO - [0m01:47:05  Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:47:05.226+0000] {eventmgr.py:62} INFO - [0m01:47:05.224827 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.01 seconds (0.01s).
[2025-01-13T01:47:05.227+0000] {logging_mixin.py:151} INFO - 01:47:05  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:47:05.227+0000] {eventmgr.py:66} ERROR - [0m01:47:05  Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:47:05.229+0000] {eventmgr.py:66} ERROR - [0m01:47:05.227272 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:47:05.230+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.230073 [debug] [MainThread]: Command `cli run` failed at 01:47:05.229900 after 3.63 seconds
[2025-01-13T01:47:05.231+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.231271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86e8ce160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc86768b610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc867815640>]}
[2025-01-13T01:47:05.233+0000] {eventmgr.py:60} DEBUG - [0m01:47:05.232738 [debug] [MainThread]: Flushing usage events
[2025-01-13T01:47:12.358+0000] {local.py:86} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2025-01-13T01:47:12.359+0000] {local.py:494} INFO - Inlets: []
[2025-01-13T01:47:12.359+0000] {local.py:495} INFO - Outlets: []
[2025-01-13T01:47:12.360+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-01-13T01:47:12.360+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2025-01-13T01:47:12.385+0000] {dag.py:3677} INFO - Setting next_dagrun for PolygonAPI_to_BigQuery to 2025-01-13T00:00:00+00:00, run_after=2025-01-14T00:00:00+00:00
[2025-01-13T01:47:12.430+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/base.py", line 268, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 654, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 509, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation did not complete with unhandled error: {result.exception}")
airflow.exceptions.AirflowException: dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'
[2025-01-13T01:47:12.435+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.run, execution_date=20250113T014436, start_date=20250113T014658, end_date=20250113T014712
[2025-01-13T01:47:12.451+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 329 for task dbt_transformation.stocks.run (dbt invocation did not complete with unhandled error: Database Error
  [Errno 21] Is a directory: '/opt/stock-market-elt-key.json'; 221)
[2025-01-13T01:47:12.490+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T01:47:12.519+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
