[2025-01-08T23:40:01.402+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:38:42.686957+00:00 [queued]>
[2025-01-08T23:40:01.412+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:38:42.686957+00:00 [queued]>
[2025-01-08T23:40:01.413+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-01-08T23:40:01.413+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-01-08T23:40:01.413+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-01-08T23:40:01.428+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.stocks_run> on 2025-01-08 23:38:42.686957+00:00
[2025-01-08T23:40:01.433+0000] {standard_task_runner.py:55} INFO - Started process 310 to run task
[2025-01-08T23:40:01.435+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.stocks_run', 'manual__2025-01-08T23:38:42.686957+00:00', '--job-id', '632', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmpemno15rt']
[2025-01-08T23:40:01.436+0000] {standard_task_runner.py:83} INFO - Job 632: Subtask dbt_transformation.stocks.stocks_run
[2025-01-08T23:40:01.498+0000] {task_command.py:388} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:38:42.686957+00:00 [running]> on host 65047f1edb18
[2025-01-08T23:40:01.566+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PolygonAPI_to_BigQuery
AIRFLOW_CTX_TASK_ID=dbt_transformation.stocks.stocks_run
AIRFLOW_CTX_EXECUTION_DATE=2025-01-08T23:38:42.686957+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-08T23:38:42.686957+00:00
[2025-01-08T23:40:01.567+0000] {log.py:232} WARNING - [[34m2025-01-08 23:40:01,567[0m] {[34mlocal.py:[0m146} INFO[0m - [33m(astronomer-cosmos)[0m - Cloning project to writable temp directory /tmp/tmpzwqqirst from /opt/***/dbt/dbt_stock_project[0m
[2025-01-08T23:40:02.003+0000] {log.py:232} WARNING - [[34m2025-01-08 23:40:02,003[0m] {[34mconfig.py:[0m139} INFO[0m - [33m(astronomer-cosmos)[0m - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml[0m
[2025-01-08T23:40:02.004+0000] {log.py:232} WARNING - [[34m2025-01-08 23:40:02,003[0m] {[34mlocal.py:[0m176} INFO[0m - [33m(astronomer-cosmos)[0m - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
From /tmp/tmpzwqqirst/dbt_project[0m
[2025-01-08T23:40:02.005+0000] {log.py:232} WARNING - [[34m2025-01-08 23:40:02,004[0m] {[34mlocal.py:[0m177} INFO[0m - [33m(astronomer-cosmos)[0m - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])[0m
[2025-01-08T23:40:02.005+0000] {log.py:232} WARNING - [[34m2025-01-08 23:40:02,005[0m] {[34msubprocess.py:[0m60} INFO[0m - [33m(astronomer-cosmos)[0m - Tmp dir root location: 
 /tmp[0m
[2025-01-08T23:40:02.006+0000] {log.py:232} WARNING - [[34m2025-01-08 23:40:02,005[0m] {[34msubprocess.py:[0m73} INFO[0m - [33m(astronomer-cosmos)[0m - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev'][0m
[2025-01-08T23:40:02.017+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 282, in execute
    result = self.build_and_run_cmd(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 194, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 182, in run_command
    cwd=tmp_project_dir,
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 130, in run_subprocess
    subprocess_result: FullOutputSubprocessResult = self.subprocess_hook.run_command(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/hooks/subprocess.py", line 81, in run_command
    preexec_fn=pre_exec,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.local/bin/dbt': '/home/airflow/.local/bin/dbt'
[2025-01-08T23:40:02.029+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.stocks_run, execution_date=20250108T233842, start_date=20250108T234001, end_date=20250108T234002
[2025-01-08T23:40:02.046+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 632 for task dbt_transformation.stocks.stocks_run ([Errno 2] No such file or directory: '/home/airflow/.local/bin/dbt': '/home/airflow/.local/bin/dbt'; 310)
[2025-01-08T23:40:02.088+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-01-08T23:40:02.118+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
