[2025-01-08T23:45:02.890+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:38:42.686957+00:00 [queued]>
[2025-01-08T23:45:02.899+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:38:42.686957+00:00 [queued]>
[2025-01-08T23:45:02.899+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-01-08T23:45:02.900+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-01-08T23:45:02.901+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-01-08T23:45:02.915+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunLocalOperator): dbt_transformation.stocks.stocks_run> on 2025-01-08 23:38:42.686957+00:00
[2025-01-08T23:45:02.919+0000] {standard_task_runner.py:55} INFO - Started process 863 to run task
[2025-01-08T23:45:02.923+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PolygonAPI_to_BigQuery', 'dbt_transformation.stocks.stocks_run', 'manual__2025-01-08T23:38:42.686957+00:00', '--job-id', '633', '--raw', '--subdir', 'DAGS_FOLDER/polygon_to_bigquery.py', '--cfg-path', '/tmp/tmppy_od_ga']
[2025-01-08T23:45:02.924+0000] {standard_task_runner.py:83} INFO - Job 633: Subtask dbt_transformation.stocks.stocks_run
[2025-01-08T23:45:02.983+0000] {task_command.py:388} INFO - Running <TaskInstance: PolygonAPI_to_BigQuery.dbt_transformation.stocks.stocks_run manual__2025-01-08T23:38:42.686957+00:00 [running]> on host 65047f1edb18
[2025-01-08T23:45:03.049+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PolygonAPI_to_BigQuery
AIRFLOW_CTX_TASK_ID=dbt_transformation.stocks.stocks_run
AIRFLOW_CTX_EXECUTION_DATE=2025-01-08T23:38:42.686957+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-08T23:38:42.686957+00:00
[2025-01-08T23:45:03.051+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:03,050[0m] {[34mlocal.py:[0m146} INFO[0m - [33m(astronomer-cosmos)[0m - Cloning project to writable temp directory /tmp/tmpcawr65hx from /opt/***/dbt/dbt_stock_project[0m
[2025-01-08T23:45:03.518+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:03,518[0m] {[34mconfig.py:[0m139} INFO[0m - [33m(astronomer-cosmos)[0m - Using user-supplied profiles.yml at /opt/***/dbt/profiles/profiles.yml[0m
[2025-01-08T23:45:03.519+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:03,519[0m] {[34mlocal.py:[0m176} INFO[0m - [33m(astronomer-cosmos)[0m - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev']
From /tmp/tmpcawr65hx/dbt_project[0m
[2025-01-08T23:45:03.520+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:03,519[0m] {[34mlocal.py:[0m177} INFO[0m - [33m(astronomer-cosmos)[0m - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])[0m
[2025-01-08T23:45:03.520+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:03,520[0m] {[34msubprocess.py:[0m60} INFO[0m - [33m(astronomer-cosmos)[0m - Tmp dir root location: 
 /tmp[0m
[2025-01-08T23:45:03.521+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:03,521[0m] {[34msubprocess.py:[0m73} INFO[0m - [33m(astronomer-cosmos)[0m - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'stocks', '--profiles-dir', '/opt/***/dbt/profiles', '--profile', 'default', '--target', 'dev'][0m
[2025-01-08T23:45:03.529+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:03,529[0m] {[34msubprocess.py:[0m84} INFO[0m - [33m(astronomer-cosmos)[0m - Command output:[0m
[2025-01-08T23:45:06.808+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:06,808[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m23:45:06  Running with dbt=1.5.11[0m
[2025-01-08T23:45:08.820+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,819[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m23:45:08  Encountered an error:[0m
[2025-01-08T23:45:08.820+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,820[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - invalid syntax (column.py, line 230)[0m
[2025-01-08T23:45:08.822+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,822[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m23:45:08  Traceback (most recent call last):[0m
[2025-01-08T23:45:08.822+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,822[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper[0m
[2025-01-08T23:45:08.823+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,823[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     result, success = func(*args, **kwargs)[0m
[2025-01-08T23:45:08.823+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,823[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper[0m
[2025-01-08T23:45:08.824+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,824[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return func(*args, **kwargs)[0m
[2025-01-08T23:45:08.825+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,824[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper[0m
[2025-01-08T23:45:08.825+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,825[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)[0m
[2025-01-08T23:45:08.826+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,826[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile[0m
[2025-01-08T23:45:08.826+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,826[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile_renderer, profile_name, profile_name_override, target_override, threads_override[0m
[2025-01-08T23:45:08.826+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,826[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render[0m
[2025-01-08T23:45:08.827+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,827[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     threads_override=threads_override,[0m
[2025-01-08T23:45:08.828+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,828[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles[0m
[2025-01-08T23:45:08.828+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,828[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     threads_override=threads_override,[0m
[2025-01-08T23:45:08.829+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,829[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info[0m
[2025-01-08T23:45:08.829+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,829[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     profile_data, profile_name, target_name[0m
[2025-01-08T23:45:08.830+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,830[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile[0m
[2025-01-08T23:45:08.830+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,830[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     cls = load_plugin(typename)[0m
[2025-01-08T23:45:08.831+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,831[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin[0m
[2025-01-08T23:45:08.831+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,831[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return FACTORY.load_plugin(name)[0m
[2025-01-08T23:45:08.832+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,832[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin[0m
[2025-01-08T23:45:08.832+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,832[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     mod: Any = import_module("." + name, "dbt.adapters")[0m
[2025-01-08T23:45:08.833+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,833[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module[0m
[2025-01-08T23:45:08.833+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,833[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     return _bootstrap._gcd_import(name[level:], package, level)[0m
[2025-01-08T23:45:08.834+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,834[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import[0m
[2025-01-08T23:45:08.834+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,834[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load[0m
[2025-01-08T23:45:08.835+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,835[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked[0m
[2025-01-08T23:45:08.835+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,835[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked[0m
[2025-01-08T23:45:08.836+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,835[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module[0m
[2025-01-08T23:45:08.836+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,836[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed[0m
[2025-01-08T23:45:08.836+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,836[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>[0m
[2025-01-08T23:45:08.837+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,837[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     from dbt.adapters.bigquery.column import BigQueryColumn  # noqa[0m
[2025-01-08T23:45:08.837+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,837[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -   File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230[0m
[2025-01-08T23:45:08.838+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,837[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -     if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):[0m
[2025-01-08T23:45:08.838+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,838[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m -                                          ^[0m
[2025-01-08T23:45:08.838+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,838[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - SyntaxError: invalid syntax[0m
[2025-01-08T23:45:08.839+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:08,839[0m] {[34msubprocess.py:[0m94} INFO[0m - [33m(astronomer-cosmos)[0m - [0m
[2025-01-08T23:45:09.900+0000] {log.py:232} WARNING - [[34m2025-01-08 23:45:09,900[0m] {[34msubprocess.py:[0m98} INFO[0m - [33m(astronomer-cosmos)[0m - Command exited with return code 2[0m
[2025-01-08T23:45:09.916+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 282, in execute
    result = self.build_and_run_cmd(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 194, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 185, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.7/site-packages/cosmos/operators/local.py", line 79, in exception_handling
    *result.full_output,
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m23:45:06  Running with dbt=1.5.11', '\x1b[0m23:45:08  Encountered an error:', 'invalid syntax (column.py, line 230)', '\x1b[0m23:45:08  Traceback (most recent call last):', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper', '    result, success = func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper', '    return func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper', '    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile', '    profile_renderer, profile_name, profile_name_override, target_override, threads_override', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info', '    profile_data, profile_name, target_name', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile', '    cls = load_plugin(typename)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin', '    return FACTORY.load_plugin(name)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin', '    mod: Any = import_module("." + name, "dbt.adapters")', '  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module', '    return _bootstrap._gcd_import(name[level:], package, level)', '  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import', '  File "<frozen importlib._bootstrap>", line 983, in _find_and_load', '  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked', '  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked', '  File "<frozen importlib._bootstrap_external>", line 728, in exec_module', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>', '    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230', '    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):', '                                         ^', 'SyntaxError: invalid syntax', '')
[2025-01-08T23:45:09.921+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=PolygonAPI_to_BigQuery, task_id=dbt_transformation.stocks.stocks_run, execution_date=20250108T233842, start_date=20250108T234502, end_date=20250108T234509
[2025-01-08T23:45:09.936+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 633 for task dbt_transformation.stocks.stocks_run (('dbt command failed. The command returned a non-zero exit code 2. Details: ', '\x1b[0m23:45:06  Running with dbt=1.5.11', '\x1b[0m23:45:08  Encountered an error:', 'invalid syntax (column.py, line 230)', '\x1b[0m23:45:08  Traceback (most recent call last):', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 86, in wrapper', '    result, success = func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 71, in wrapper', '    return func(*args, **kwargs)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/cli/requires.py", line 139, in wrapper', '    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/runtime.py", line 70, in load_profile', '    profile_renderer, profile_name, profile_name_override, target_override, threads_override', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 441, in render', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 407, in from_raw_profiles', '    threads_override=threads_override,', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 356, in from_raw_profile_info', '    profile_data, profile_name, target_name', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile', '    cls = load_plugin(typename)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 209, in load_plugin', '    return FACTORY.load_plugin(name)', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/factory.py", line 58, in load_plugin', '    mod: Any = import_module("." + name, "dbt.adapters")', '  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module', '    return _bootstrap._gcd_import(name[level:], package, level)', '  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import', '  File "<frozen importlib._bootstrap>", line 983, in _find_and_load', '  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked', '  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked', '  File "<frozen importlib._bootstrap_external>", line 728, in exec_module', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>', '    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa', '  File "/home/***/.local/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230', '    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):', '                                         ^', 'SyntaxError: invalid syntax', ''); 863)
[2025-01-08T23:45:09.962+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-01-08T23:45:09.991+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
